allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  argon2: true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
